### ISSUE TITLE
Editing possibilities of the package

### ISSUE THREAD

**Issue by den-ree** [heestand-xyz/AsyncGraphics#11]
Hi @heestand-xyz , 
I found the package very capable, but for me, it's hard to find out if it's possible to develop an image and video editor with the following features: 
1. Basic Adjustments ( Brightness, contrast, saturation, shadows, highlights, exposure, ..)
2. Crop 
3. Trim (for videos)
4. Adding text 
5. Adding image stickers

**Comment by heestand-xyz** [comment]
Hi, thanks, yeah I should write some more articles.
Regarding the features you listed, all of them are possible, tho I can see that it can be hard to get started.
I built [Render](https://apps.apple.com/app/render-video-composer/id6444799341) with AsyncGraphics. Check out [levels](https://heestand-xyz.github.io/AsyncGraphics-Docs/documentation/asyncgraphics/graphic#levels) and the [video editing article](https://heestand-xyz.github.io/AsyncGraphics-Docs/documentation/asyncgraphics/videoediting).
