### ISSUE TITLE
Video Playback Example throws Error

### ISSUE THREAD

**Issue by nkleemann** [heestand-xyz/AsyncGraphics#8]
The example you give [here](https://heestand-xyz.github.io/AsyncGraphics-Docs/documentation/asyncgraphics/videoplayback/) throws errors on the line `return GraphicVideoPlayer(url: url, options: options)`: 

1: 'async' call in a function that does not support concurrency.
2: Call can throw, but it is not marked with 'try' and the error is not handled

I could fix error # 2 but struggle with fixing the first error.

I'm on Xcode 15.2, macOS 13.6.4.

**Comment by heestand-xyz** [comment]
Hi, thanks for reporting the issue. I've fixed it in verison `2.0.3`, will be avalible soon!
In the new verison the initalizer is not async or throwing, tho you need to call a setup function before playing:
```swift
try await videoPlayer.setup()
```

**Comment by heestand-xyz** [comment]
Version `2.0.3` is now available and the docs are updated.
