### ISSUE TITLE
`levels` effect not consistent between video & camera source

### ISSUE THREAD

**Issue by nkleemann** [heestand-xyz/AsyncGraphics#9]
When processing frames from `Graphic.playVideo` with the `levels` effect, and setting the `gamma` uniform in the levels shader to values greater than 1, the image does not get inverted. But when you obtain frames from the camera, the image does get inverted.

This is just a small issue, but swapping between video/camera sources might be common during development to prototype effects. So it might be worth looking into parity between the two frame sources.

Example:
```swift
let processed = try await frame.levels(
            brightness: 2,
            darkness: 0.6,
            contrast: 0.2,
            gamma: 1.2 
        )
```

**Comment by heestand-xyz** [comment]
Interesting, I'll try to look into this, thanks!

**Comment by heestand-xyz** [comment]
I think it has to do with high bit graphics, you can force it to 8bit here: https://heestand-xyz.github.io/AsyncGraphics-Docs/documentation/asyncgraphics/graphic/bits(_:)

**Comment by nkleemann** [comment]
Will try it out, thanks!
